# Generated by Django 2.0.6 on 2018-06-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_configuration_name'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='website.Configuration'),
            preserve_default=False,
        ),
    ]
